<?php

namespace Database\Seeders;

use App\Models\AssessmentQuestion;
use App\Models\AssessmentType;
use Illuminate\Database\Seeder;

class RiasecQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $riasecType = AssessmentType::where('slug', 'riasec')->first();

        if (! $riasecType) {
            $this->command->warn('RIASEC assessment type not found. Run AssessmentTypeSeeder first.');

            return;
        }

        $questions = $this->getQuestions();

        foreach ($questions as $index => $questionData) {
            // Ensure valid question_type for current schema
            $questionData['question_type'] = 'rating_scale';

            AssessmentQuestion::updateOrCreate(
                [
                    'assessment_type_id' => $riasecType->id,
                    'order' => $index + 1,
                ],
                $questionData
            );
        }

        $this->command->info('Created '.count($questions).' RIASEC questions.');
    }

    protected function getQuestions(): array
    {
        return [
            // Realistic (R) Questions - 10 questions
            [
                'question_text' => 'I enjoy working with tools and machinery',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer hands-on practical tasks over theoretical discussions',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I would enjoy working outdoors in nature',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'Fixing or building things gives me satisfaction',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I am physically coordinated and enjoy athletic activities',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer working with concrete objects rather than abstract ideas',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'Operating vehicles or heavy equipment interests me',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I like seeing tangible results from my work',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'Working with my hands is more appealing than desk work',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],
            [
                'question_text' => 'I enjoy troubleshooting mechanical or technical problems',
                'question_type' => 'likert_scale',
                'category' => 'Realistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['R' => 0],
                    2 => ['R' => 1],
                    3 => ['R' => 2],
                    4 => ['R' => 3],
                    5 => ['R' => 4],
                ],
            ],

            // Investigative (I) Questions - 10 questions
            [
                'question_text' => 'I enjoy solving complex problems and puzzles',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I am curious about how things work',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'Conducting research and analyzing data appeals to me',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer to think things through before taking action',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I enjoy learning about scientific concepts and theories',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'Working in a laboratory environment interests me',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I like exploring abstract ideas and theories',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I am skilled at identifying patterns in information',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'Understanding cause-and-effect relationships fascinates me',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer independent work that requires analytical thinking',
                'question_type' => 'likert_scale',
                'category' => 'Investigative',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['I' => 0],
                    2 => ['I' => 1],
                    3 => ['I' => 2],
                    4 => ['I' => 3],
                    5 => ['I' => 4],
                ],
            ],

            // Artistic (A) Questions - 10 questions
            [
                'question_text' => 'I enjoy expressing myself through creative outlets',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I appreciate and engage with art, music, or literature',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer unstructured environments where I can be innovative',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'Design and aesthetics are important to me',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I like coming up with original ideas and concepts',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'Working in creative fields like writing, design, or performing arts appeals to me',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I am drawn to unconventional approaches and thinking',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I value emotional expression and imagination',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'Routine and repetition stifle my creativity',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],
            [
                'question_text' => 'I enjoy attending cultural events and exhibitions',
                'question_type' => 'likert_scale',
                'category' => 'Artistic',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['A' => 0],
                    2 => ['A' => 1],
                    3 => ['A' => 2],
                    4 => ['A' => 3],
                    5 => ['A' => 4],
                ],
            ],

            // Social (S) Questions - 10 questions
            [
                'question_text' => 'I enjoy helping others solve their problems',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'Teaching and training others is rewarding to me',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'I am good at understanding and empathizing with others',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'Careers in healthcare, counseling, or social work interest me',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'I prefer working in teams to accomplish goals',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'Making a positive impact on people\'s lives is important to me',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'I am patient and supportive when working with others',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'Community service and volunteer work appeal to me',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'I enjoy facilitating group discussions and activities',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],
            [
                'question_text' => 'Building relationships is a strength of mine',
                'question_type' => 'likert_scale',
                'category' => 'Social',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['S' => 0],
                    2 => ['S' => 1],
                    3 => ['S' => 2],
                    4 => ['S' => 3],
                    5 => ['S' => 4],
                ],
            ],

            // Enterprising (E) Questions - 10 questions
            [
                'question_text' => 'I enjoy leading and influencing others',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'Starting my own business or project excites me',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'I am comfortable taking risks to achieve goals',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'Persuading and negotiating come naturally to me',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'I am motivated by competition and achieving success',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'Sales, marketing, or management roles appeal to me',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'I am assertive and confident in my abilities',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'Financial gain and recognition are important motivators',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'I enjoy setting ambitious goals and working to achieve them',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],
            [
                'question_text' => 'I thrive in fast-paced, dynamic environments',
                'question_type' => 'likert_scale',
                'category' => 'Enterprising',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['E' => 0],
                    2 => ['E' => 1],
                    3 => ['E' => 2],
                    4 => ['E' => 3],
                    5 => ['E' => 4],
                ],
            ],

            // Conventional (C) Questions - 10 questions
            [
                'question_text' => 'I prefer structured and organized environments',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'I am good at managing data and maintaining records',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'Following established procedures and rules is important to me',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'I pay close attention to details and accuracy',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'Working with numbers, spreadsheets, or databases appeals to me',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'I like clearly defined tasks with measurable outcomes',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'Efficiency and orderliness matter to me',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'Office work and administrative tasks suit me well',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'I am reliable and methodical in my approach',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
            [
                'question_text' => 'I find security in predictable routines and schedules',
                'question_type' => 'likert_scale',
                'category' => 'Conventional',
                'options' => [
                    ['value' => 1, 'label' => 'Strongly Disagree'],
                    ['value' => 2, 'label' => 'Disagree'],
                    ['value' => 3, 'label' => 'Neutral'],
                    ['value' => 4, 'label' => 'Agree'],
                    ['value' => 5, 'label' => 'Strongly Agree'],
                ],
                'scoring_map' => [
                    1 => ['C' => 0],
                    2 => ['C' => 1],
                    3 => ['C' => 2],
                    4 => ['C' => 3],
                    5 => ['C' => 4],
                ],
            ],
        ];
    }
}
